name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy resources directory to dist
      run: |
        cp -r resources dist/
        ls -lhRt

    - name: Compress executable and resources
      run: |
        cd dist && zip -r youtube-dlp-gui.zip youtube-dlp-gui.exe resources

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.5
        release_name: Release v1.0.5
        body: |
          Version 1.0.5, compiled for windows users :)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/youtube-dlp-gui.zip
        asset_name: youtube-dlp-gui.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
